### PR TITLE
SQL injection fix: Coerce offset and limit values to integers

### LINKED ISSUE #73: SQL injection possible with limit() on MySQL
**The `limit()` query method is susceptible to catastrophic SQL injection with MySQL.**

For example, given an ActiveRecord model `User` for a table `users`:
```php
UserQuery::create()->limit('1;DROP TABLE users')->find();
```
This will drop the `users` table!

The cause appears to be a lack of integer casting of the limit input in either [`Propel\Runtime\ActiveQuery\Criteria::setLimit()`](https://github.com/propelorm/Propel3/blob/master/src/Propel/Runtime/ActiveQuery/Criteria.php#L1246-L1252) or in [`Propel\Runtime\Adapter\Pdo\MysqlAdapter::applyLimit()`](https://github.com/propelorm/Propel3/blob/master/src/Propel/Runtime/Adapter/Pdo/MysqlAdapter.php#L121-L128). The code comments there seem to imply that casting was avoided due to overflow issues with 32-bit integers.

This is surprising behavior since one of the primary purposes of an ORM is to prevent basic SQL injection.

**This affects all versions of Propel: 1.x, 2.x, and 3.**

Related:
- https://github.com/propelorm/Propel/issues/1052
- https://github.com/propelorm/Propel2/issues/1463

### PR DESCRIPTION
**Pull request by mpetrovich**
These changes fix vulnerabilities in the MySQL adapter that allow SQL injection via query `limit()` methods:
```php
UserQuery::create()->limit('1;DROP TABLE users')->find();
```

Fixes were applied to both the MySQL adapter and the database-agnostic `Criteria` class to prevent other/future adapters from being susceptible to similar SQL injection vulnerabilities.

This pull request is a similar fix to the ones for Propel 1.x and 2.x

Fixes: https://github.com/propelorm/Propel3/issues/73
Related:
- https://github.com/propelorm/Propel/pull/1054
- https://github.com/propelorm/Propel2/pull/1465

### CODE REVIEW

File: src/Propel/Runtime/ActiveQuery/Criteria.php [hunk 1]
```diff
@@ -1245,8 +1245,7 @@ public function isSingleRecord()
      */
     public function setLimit($limit)
     {
-        // TODO: do we enforce int here? 32bit issue if we do
-        $this->limit = $limit;
+        $this->limit = (int) $limit;
```
Comment (mpetrovich) [inline src/Propel/Runtime/ActiveQuery/Criteria.php:1248]: _Maintainers:_
Can anyone provide some context around this comment? My unit tests show that no truncation occurs for large values like 64-bit integers.

**Comment by mpetrovich** [comment]
The build failures are all over the place, not sure what's going on here.

**Comment by marcj** [comment]
This is ok, it's edgy development branch at the moment with a lot of failing tests.

**Comment by marcj** [comment]
Thanks anyways!
