### PR TITLE
fix initSqlite

### LINKED ISSUE #7: removing leading space within the sqlite dsn
See https://github.com/propelorm/Propel2/pull/1292

### PR DESCRIPTION
**Pull request by Byteceptikus**
fixes #7

### CODE REVIEW

**Comment by marcj** [comment]
Thanks!

File: src/Propel/Generator/Command/InitCommand.php [hunk 1]
```diff
@@ -174,7 +174,7 @@ private function initSqlite(OutputInterface $output, DialogHelper $dialog)
     {
         $path = $dialog->ask($output, 'Where should the sqlite database be stored?', getcwd() . '/my.app.sq3');
 
-        return sprintf('sqlite:', $path);
+        return sprintf('sqlite:%', $path);
```
Comment (staabm) [inline src/Propel/Generator/Command/InitCommand.php:177]: `%s` ..?

Comment (marcj) [reply src/Propel/Generator/Command/InitCommand.php:177]: lol
